### PR TITLE
Move dsl default location to project root and minor Melange related refactoring

### PR DESCRIPTION
**Pull request by dvojtise**
This PR changes the default location for .dsl files.

The wizards and Melange will now place them at the root of the project.

This contributes to fix https://github.com/eclipse/gemoc-studio-modeldebugging/issues/65

This PR also does some minor code cleanup by removing unnecessary dependencies to Melange

This PR comes with PR https://github.com/eclipse/gemoc-studio/pull/124

### CODE REVIEW

**Comment by ebousse** [comment]
Just curious: why does the PR have so many added lines (+669) for very few removed lines (−43)? Shouldn't it simply change existing code to adapt to the new path?

**Comment by dvojtise** [comment]
True, I forgot to mention 2 additional stuff I did commit when writing this PR:
- reintroduce a Jenkins file at the root of this repo. It helps to trigger the build on jenkins even if there is no branch with the corresponding name in the repo gemoc-studio. However, this is still not perfect because this jenkinsfile must be copied in each repo.
- refactored some code that was coming from Melange, I introduced a class AbstractNewProjectWizardWithTemplates that implements INewWizard in order to replace the use of NewMelangeProjectWizard. This goes in direction of removing unnecessary dependencies to Melange

**Comment by ebousse** [comment]
Ah I see, I understand better then. Maybe then you should change the PR title, to have a cleaner squash and changelog afterwards?

**Comment by ebousse** [comment]
Also two tests appear to fail: https://ci.eclipse.org/gemoc/job/gemoc-studio/job/move_dsl_default_location_to_project_root/

With the same error: `Unexpected marker: Cannot cast from EObjectAdapter to StateAdapter on /org.eclipse.gemoc.sample.legacyfsm.xfsm/src-gen/org/eclipse/gemoc/sample/legacyfsm/xfsm/adapters/xfsmmt/XfsmMTAdaptersFactory.java`

Some problems in the Melange generated code. Could it be caused to your Melange-related changes? This would be strange since this seems to be cause by core Melange services.

**Comment by dvojtise** [comment]
Yes, I'm on it. I did not intend to accept a PR with failed tests :wink:  (this is just a pain to have to switch between 2 branches when working on 2 PRs and try to validate them locally)

I'll try to get the Eclipse package and regenerate everything for the example and not just the runtime

**Comment by ebousse** [comment]
OK great :) good luck with bug hunting!

**Comment by dvojtise** [comment]
tests are now successful and ready for review, squash and merge  :smile:

**Pull request merged**
