### PR TITLE
Fix updating of Sirius views during debugging

### PR DESCRIPTION
**Pull request by szschaler**
Addresses issue #96 

Signed-off-by: Steffen Zschaler <steffen.zschaler@kcl.ac.uk>

### CODE REVIEW

**Comment by dvojtise** [comment]
I've created a test branch _szschaler-fix_updating_sirius_view_during_debugging_ by following instructions on https://github.com/eclipse/gemoc-studio/wiki/Official-commiter-memo

let's wait for the CI results (with the corresponding branch on https://ci.eclipse.org/gemoc/job/gemoc-studio-integration/) before accepting this :slightly_smiling_face:

**Comment by szschaler** [comment]
Thanks and apologies for not reading the documentation. 

Looks like the Jenkins build fails when trying to check out from the repo. Do I need to add keys or something?

**Comment by dvojtise** [comment]
No, this is OK for the build, your branch was close enough to the head. The failed build was due to a previous PR that was split in 3 repositories and I forgot to accept one. It passes now.

**Comment by szschaler** [comment]
So is this ready to be merged?

**Pull request merged**
