### PR TITLE
[Event Manager PR#1] Support for execution step parameters + misc.

### PR DESCRIPTION
**Pull request by d-leroy**
## Description

Introduces some changes in the execution framework necessary for the integration of the event manager.

## Changes

This commit brings the following changes:
 - add the parameters of an execution step to methods handling such calls,
 - better implementation of the `findOperation` method in `AbstractSequentialExecutionEngine`, supporting execution rule overloading,
 - add a method to `GemocRunningEnginesRegistry` to specify an engine's name when registering it,
 - add a corresponding `_name` field in `AbstractExecutionEngine`,
 - add some methods to `IRunConfiguration` to support `Map` and `Set` launch configuration attributes,
 - remove some warnings in `org.eclipse.gemoc.executionframework.ui`.

### CODE REVIEW

**Comment by ebousse** [comment]
The diff is very noisy due to the big reformatting pass you made. As far as I can see, the only real change is on `executeOperation` right? The change there looks good to me.

I've pulled your branch on the Eclipse repository to trigger a build:
https://ci.eclipse.org/gemoc/job/gemoc-studio-integration/job/event-manager-execution-framework/

The build passes, but some test cases are failing. It's probably because of the flakiness of the test suite though, since I see a "timeout". I've triggered a new build to see if we can make it green.

But I'm almost surprised the build passes! Shouldn't the K3/ALE/other engines change their code because of the `executeOperation` change?

**Comment by ebousse** [comment]
@dvojtise WDYT? I suggest we merge.

**Comment by dvojtise** [comment]
I approve too :-)

**Comment by ebousse** [comment]
However we still have this:
>  eclipsefdn/eca — The author(s) of the pull request is not covered by necessary legal agreements in order to proceed. 

@d-leroy Is your email (dorian.leroy@irisa.fr) stil registered at Eclipse?

**Comment by ebousse** [comment]
> However we still have this:
> 
> > eclipsefdn/eca — The author(s) of the pull request is not covered by necessary legal agreements in order to proceed.
> 
> @d-leroy Is your email ([dorian.leroy@irisa.fr](mailto:dorian.leroy@irisa.fr)) stil registered at Eclipse?

Fixed. Let's merge :confetti_ball:

**Pull request merged**
