### PR TITLE
Improve gemoc project template wizard

### PR DESCRIPTION
**Pull request by dvojtise**
This PR add several improvment in the templates of the GEMOC project wizard.

- improved messages (added a (*) to indicate mandatory fields
- added new template for melange with 2 languages (with inheritance)

This PR can be tested using the result of the following CI job
https://ci.eclipse.org/gemoc/job/gemoc-studio/job/improve-gemoc-project-template-wizard/

This PR relies on the PR#9 on gemoc-studio: https://github.com/eclipse/gemoc-studio/pull/9

### CODE REVIEW

**Comment by fcoulon** [comment]
Seems there is no .melange when creating a new sequential project

**Comment by dvojtise** [comment]
which of the 2 templates did you use ?

**Comment by fcoulon** [comment]
I tried with the Studio from the link above.
I only have `Simple Gemoc Sequential project` in the template page

**Comment by dvojtise** [comment]
Mhh, I may have forgot to commit something or need to force a build on the CI

**Comment by dvojtise** [comment]
I've forced a build on the CI

in addition I've improved the templates
- better default values in case of empty ecore
- improved comments in the generated files (ie. tries to teach the user how to use the languages for typical situations)

**Comment by fcoulon** [comment]
Works for me

**Comment by ebousse** [comment]
Just tested quickly, and I tried with a language name `aaa`, which creates a Melange error because the language name should start with an upper case. Maybe this check could be added in the wizard? Maybe the Melange validator code can be reused for the fields of the wizard?

Other than that, seems to work well!

Other than that, after this PR is merged, I would advise opening an issue on the clarity of the names given to the wizards (as we discussed IRL). The two choices are only made different using the word "Simple", which is clearly not enough. The descriptions of the choices are not enough either.

**Pull request merged**
