### PR TITLE
[Event Manager PR#2] Event manager plugin

### PR DESCRIPTION
**Pull request by d-leroy**
## Description

Adds the event manager, an engine addon able to send events to and emit events from running models.

## Changes

This commit brings the following changes:
 - add the `WaitingForEvent` engine status,
 - add the `GenericEventManager`, which is an `IEngineAddon`,
 - add extension points to be used by languages to provide the implementation and subtyping relationships,
 - add extension point to be used by metalanguages to provide rule executors allowing implementation relationship to call execution rules from the semantics.

### CODE REVIEW

**Comment by ebousse** [comment]
Started a CI build here: https://ci.eclipse.org/gemoc/job/gemoc-studio-integration/job/event-manager-plugin/

**Comment by ebousse** [comment]
Build is OK, test cases still failing for no clear reason.

**Comment by dvojtise** [comment]
there are 3 failing tests instead of the usual 2 ones :-/

**Comment by ebousse** [comment]
I've downloaded the resulting studio, and I could manually run the K3FSM example without problem. 
I'll try to see how to reproduce the test cases…

**Comment by ebousse** [comment]
OK maybe I found a problem (possibly unrelated to this PR), with the Engine Status UI:
Capture d’écran de 2021-04-09 09-29-05

Here I've finished an execution, the engine is stopped. **The interesting part are the two buttons to dispose stopped engines, in the top right corner.** It turns out that while the button to dispose _all_ stopped engine works as expected, the button to dispose only _one_ stopped engine is always disabled, even when we are selecting a stopped engine.

@dvojtise Are your test scenarios using this button?

**Comment by dvojtise** [comment]
apparently no, only one test use it and it uses the "dispose all"

BTW, once a test fails, the status of the workbench running the test suites looks bad (not correctly fully reset ?), thus following tests are irrelevant, one of the problem we have is that this quite hard to really know in which order they run (expect looking in the console)

**Comment by ebousse** [comment]
Indeed, here are the relevant lines in the test case:
```xtend
	def static void closeAndClearEngine() {
		val runningEnginesRegistry = org.eclipse.gemoc.executionframework.engine.Activator.getDefault().gemocRunningEngineRegistry;
		
		// stop engine and clear using the engine status view
		bot.viewByTitle("Gemoc Engines Status").show();
		bot.toolbarButtonWithTooltip("Stop selected engines").click();
		bot.toolbarButtonWithTooltip("Dispose all stopped engines").click();
		
		assertTrue("runningEngineRegistry not empty " +runningEnginesRegistry.runningEngines,  runningEnginesRegistry.runningEngines.size == 0)
	}
```
So the button `"Stop selected engines"` is indeed used, but then the `"Dispose all stopped engines"` is used right after, so that should not be a problem. 

But I've probably found a bug for the master branch :).

**Comment by ebousse** [comment]
Looking at the test logs, I think a relevant line is this one:
`org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find shell matching: with text 'Confirm Perspective Switch'`

Is this about the "switch to debug perspective" pop-up? If so, maybe the test case is wrongly expecting that this pop-up appears, while it does not?

**Comment by ebousse** [comment]
OK I found the problem, this actually makes sense.

We have this line in the test cases:
```xtend
bot.tree().getTreeItem("K3FSM - TwoStatesUpcast(abababa) [Executable model with GEMOC Java engine]").getNode("Gemoc debug target").getNode("Model debugging").waitNode("[FSM] TwoStateUpcast#initializeModel()").select();
```
And we have this in the model execution stack:
Capture d’écran de 2021-04-09 10-46-09

Can you spot the difference? We have a `[]` that is now apparent, because of Dorian's changes :).

So we need also a PR in the gemoc-studio repository, to update test cases.

**Comment by dvojtise** [comment]
well spotted ! we definitively need some tool to help to see the content of the UI we an assertion fails, the screenshot isn't enough as the information might be hidden (too small windows) or invisible (actual SWT name of widgets )

**Comment by ebousse** [comment]
> well spotted ! we definitively need some tool to help to see the content of the UI when an assertion fails, the screenshot isn't enough as the information might be hidden (too small windows) or invisible (actual SWT name of widgets )

I had to execute the test suite locally to understand what was wrong. Indeed, better screenshots or videos could help.

I've fixed the test case is a branch on _gemoc-studio_, and a new build has started: https://ci.eclipse.org/gemoc/job/gemoc-studio-integration/job/event-manager-plugin/3/

Fingers crossed.

**Comment by ebousse** [comment]
We still have to test cases failing:
. org.eclipse.gemoc.studio.tests.system.lwb.feature.GenerateLangRuntime4OfficialExampleMelangeK3FSM_Test.test02_GenerateAllMelange_usingClickOnMelangeFile_NoErrorsInWorkspace 
. org.eclipse.gemoc.studio.tests.system.mwb.userstory.DeployOfficialExampleK3FSM_Test.test02_DebugPredefinedK3Fsm_TwoStatesUpCast_Model_some_steps_and_stop

I managed to run `test02_GenerateAllMelange_usingClickOnMelangeFile_NoErrorsInWorkspace` on my computer without any error

I couldn't run `test02_DebugPredefinedK3Fsm_TwoStatesUpCast_Model_some_steps_and_stop` for some reason (it fails before even starting the actual test case, but I've done the same steps manually, and everything is fine.

I think we can merge. @dvojtise WDYT?

**Comment by dvojtise** [comment]
ok for merge, we are even with the previous test status

(I also have te same behavior, ok on my computer but fail on CI, I'm trying to improve failure reporting messages in a separate PR)

**Pull request merged**
