### PR TITLE
Replace Melange by DSL files in the role of entry point for the studio

### PR DESCRIPTION
**Pull request by fcoulon**
Signed-off-by: Fabien Coulon <fabien.coulon@inria.fr>

### CODE REVIEW

**Comment by ebousse** [comment]
As discussed, try to fix:
- Missing 's' to to the keyword `semantic` in the language syntax
- Conflict between the `.dsl` extensions of GEMOC and Ale. We need to decide which one to rename:
    - `.gemocdsl` for GEMOC and  `.dsl` for ALE?
    - `.dsl` for GEMOC and `.aledsl` or `.aleconfig` for ALE?

**Comment by fcoulon** [comment]
This should be fine with https://github.com/eclipse/gemoc-studio/pull/39 and https://github.com/gemoc/ale-lang/commit/165b6e1b96475d5f45effc4898e6f0156214a0d2

**Comment by ebousse** [comment]
Tests are failing in this branch: https://ci.inria.fr/gemoc/job/gemoc-studio-eclipsefork/job/dslfile/31/testReport/

I suppose we have to adapt the tests?

**Comment by fcoulon** [comment]
I merged the 'dslfile' branch in Melange repo.
We still have to promote last Melange build/update Gemoc pom.xml I guess

**Comment by ebousse** [comment]
I have triggered a build on the Melange CI in order to then trigger a promotion, but it seems that tests are failing in Melange as well https://ci.inria.fr/k3al/view/Melange/job/melange-master/683/testReport/

**Comment by ebousse** [comment]
@fcoulon : @dvojtise has solved in master the problems that were causing the tests to fail, could you merge master in your branch, solve the conflicts, and push again to see whether the tests pass on your branch now?

**Comment by ebousse** [comment]
So, after some quick cleanups in the forked repositories (pulls from `eclipse:master`, removal of the old `dslfile` branch on the forked gemoc-studio repo), I started a new build on the Inria CI, and some tests still fail: https://ci.inria.fr/gemoc/job/gemoc-studio-eclipsefork/job/dslfile/36/console

@fcoulon could you run the tests on your machine to find out what is the problem, and to fix either the code or the tests?

**Comment by fcoulon** [comment]
Hmm well...
https://github.com/gemoc/gemoc-studio-eclipsefork/blob/dslfile.bak/gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system/src/org/eclipse/gemoc/studio/tests/system/lwb/userstory/CreateSingleSequentialLanguageFromOfficialFSM_Test.xtend#L144

**Comment by dvojtise** [comment]
right the test 03 should be removed from the CreateSingleSequentialLanguageFromOfficialFSM_Test

**Comment by ebousse** [comment]
Should it? Don't we try to make the melange-based examples still work, since we are still supposed to support Melange?

**Comment by fcoulon** [comment]
CreateSingleSequentialLanguageFromOfficialFSM_Test use the wizard to create a new Sequential project from model + k3dsa project, am I right?

**Comment by dvojtise** [comment]
Well  right too,
Actually, we need to add another template in the new GEMOC Sequential xDSML Project wizard

It was changed without taking into account the 2 options and switched from one to another (partially)

image



previous templates should be maintained and clarified (ie this is a Melange project)and a new one should be introduced for dsl only projects

and a new test should be added for it ...

**Comment by dvojtise** [comment]
I do it right now in a branch ...

**Comment by fcoulon** [comment]
Yes I replaced the generated .melange by a .dsl in the New Project template

**Comment by dvojtise** [comment]
added companion pull request in gemoc-studio https://github.com/eclipse/gemoc-studio/pull/70

**Pull request merged**
