### PR TITLE
Patch mutable field extractor for pure k3 project

### PR DESCRIPTION
**Pull request by dvojtise**
This patch uses dsl project classpath for mutable field search

The search of mutable fields via melange cannot work with project not using melange.

Note:
the file IntrospectiveMutableFieldExtractor still has some suspicious call to MelangeHelper (in `private def Map<Class<?>, List<Class<?>>> getStaticHelperClasses(EObject target) {` but this is not used in my current example...

### CODE REVIEW

**Comment by ebousse** [comment]
I just had a quick look in `MelangeHelper`, and it seems now that despite the name it only provides services for DSL files.

Suggestion: could you move all operations of `MelangeHelper` into `DslHelper`? This PR is a good opportunity, since this bug was due to remaining melange-specific code anyway.

**Comment by ebousse** [comment]
Also the PR title could be less K3 specific, since it is not directly related to K3

**Comment by dvojtise** [comment]
I've moved some code from MelangeHelper to a new K3DslHelper as this is K3 specific code (dealing with aspects and K3 annotations.)
I've set up a hierarchy _MelangeHelper_ extends _K3DslHelper_ extends _DslHelper_

The code is now clearer about the actual technology it requires.

However some code cannot be moved (for ex: getLanguageURI() and other method related to URI such as getNativeLanguagesUsedByResource() ) because, unlike melange extension point, the extension point used to register dsl file does not contain URI information.

(may be we can mimic this by opening the ecore files referenced by the dsl file, but this is another refactoring that cannot be include in this PR as its initial intend is to fix the code in order to work with pure K3 languages)

**Comment by ebousse** [comment]
Looks great! However I don't see why we need the hierarchy "MelangeHelper extends K3DslHelper extends DslHelper"? Since everything is static, inheritance is useless here, isn't it? Why not just use imports?

**Comment by ebousse** [comment]
Thanks for the change, I do feel it's better this way :)

Let's merge then!

**Pull request merged**
