### PR TITLE
New plug-in for validation in GEMOC Studio

### PR DESCRIPTION
**Pull request by Kairides**
To perform validation on DSLs during their creation, whatever the meta-programming approach used, we have created an Eclipse extension point allowing other plug-ins to add validation rules to the DslValidator.

The extension point provides two interfaces, three classes and an enumeration used by the plug-ins that extends the extension poinr to create rules and add them to the DslValidator.
class_diagram(v2)

The first inteface is IRuleProvider, this interface provides validation rules to be performed by the DslValidator. These validation rules implement the second interface.

The second interfce IRule, allows to perform checks on a DSL and its entries, it send back a message that the DslValidator will then display on the GEMOC Studio. These messages are instances of the Message class.

The Message class allows the validation rules to send information regarding the creation of a DSL, according to a specific meta-programming approach, to the DslValidator. A message sent by a validation rule can for instance mention the lack of an Ecore meta-model, if the chosen meta-programming approach uses an Ecore meta-model. These messages use a severity to indicate to the DslValidator how to display them on the GEMOC Studio, the different possible values for the severity are provided by the Severity enumeration.

The Severity enumeration allow the DslValidato to know of what type a message sent by a validation rule is, this enumeration provides four values:
- ERROR,
- WARNING,
- INFO and
- DEFAULT

Each severity is displayed differently. A message with a severity ERROR will be displayed as an error in the GEMOC Studio,

error

a message with a severity WARNING will be displayed as a warning,

warning

a message with a severity INFO will be displayed as an information,

info

and a message with a severity DEFAULT won't be displayed as this severity is used if a validation rule does not detect anything abnormal for its meta-programming approach.

Two other classes are provided by the extension point. These two classes, EcoreRuleProvider and EcoreRule, provide checks on the "ecore" entry in the dsl file for meta-programming approaches that use Ecore meta-model.

To use these RuleProviders, we have added a mandatory entry "metaprog" for the dsl file,

metaprog

this entry takes the name of a meta-programming approach implemented added to GEMOC and gather the RuleProvider this approach provides.
The DslValidator will then perform its regular checks then execute every validation rules th RuleProvider gave and display their message on the GEMOC Studio.

Example of an AleRuleProvider and AleRule: https://gist.github.com/Kairides/3d3f94928ee99a5ac42107fa88c5956f

signed-off-by Ronan Guéguen <gueguen.ronan1@gmail.com>

### CODE REVIEW

**Comment by dvojtise** [comment]
This is pretty cool as it contributes to several long awaited features such as https://github.com/eclipse/gemoc-studio/issues/54 https://github.com/eclipse/gemoc-studio/issues/37 https://github.com/eclipse/gemoc-studio/issues/91

1/ however, can you first fix all git commit messages to include the **signed-off-by** as the last part of **each commit message** (and make sure they point to the email you used to sign the eclipse commiter agreement) (you added it to the pull request but actually, this must be the last line of every commit message in order to be added to the ip log and taken into account by the bot)

2/ It raises some points about where to define "metaprog" types and give them explicit but short  names (cf. https://github.com/eclipse/gemoc-studio/issues/54) and how to reuse rules that are commons to metaprog (ex: k3 is is by javaengine and moccml, ecore is currently used by all known engines, ...)  however, this can be handled later ;-)

**Comment by ebousse** [comment]
> 1/ however, can you first fix all git commit messages to include the **signed-off-by** as the last part of **each commit message** (and make sure they point to the email you used to sign the eclipse commiter agreement) (you added it to the pull request but actually, this must be the last line of every commit message in order to be added to the ip log and taken into account by the bot)

What if we squash and merge? in that case don't we only need the final unique commit to have the "signed-off-by"?

> 2/ It raises some points about where to define "metaprog" types and give them explicit but short names (cf. [eclipse/gemoc-studio#54](https://github.com/eclipse/gemoc-studio/issues/54)) and how to reuse rules that are commons to metaprog (ex: k3 is is by javaengine and moccml, ecore is currently used by all known engines, ...) however, this can be handled later ;-)

- At the moment the ID (or short name) of an approach is defined in the extension directly. Each execution engine will get its own extension eventually.
- Reusing rule is indeed not a simple matter. For the moment, reusable rules (that is, Ecore validation rules) are put in gemoc-studio-modeldebugging. But this clearly cannot work for rules that have dependencies (eg. a dependency to k3, as you mention).

**Comment by dvojtise** [comment]
1/ Squash and merge is ok if we are _sure_ that the email is ok (ie. the email is correctly found in the eclipse commiter), but as the bot currently says "no", I'm not sure :-( I would be happy if I can see at least one PR with the very same sign-off passing in the bot validation. 

2/ such rules should be put in modeldebugging too, but in specific plugins that clearly indicates the dependency (like org.eclipse.gemoc.executionframework.extensions.sirius ) so an engine is free to depend on it or not.  The name and location of such common/reussable/extension can probably be discussed :-)

**Comment by ebousse** [comment]
> 1/ Squash and merge is ok if we are _sure_ that the email is ok (ie. the email is correctly found in the eclipse commiter), but as the bot currently says "no", I'm not sure disappointed I would be happy if I can see at least one PR with the very same signed-off passing in the bot validation.

Fair enough. @Kairides could you create a "fake" small second PR with only one commit, and where the commit message has a proper "signed-off-by" message at the end?

> 2/ such rules should be put in modeldebugging too, but in specific plugins that clearly indicates the dependency (like org.eclipse.gemoc.executionframework.extensions.sirius ) so an engine is free to depend on it or not. The name and location of such common/reussable/extension can probably be discussed smiley

Yes we can simply put them in dedicated plugins each with its own set of dependencies, you are right. Sounds good to me!

**Comment by Kairides** [comment]
I created the fake PR, but I will create a new pull request since there was some elements I want to edit.

**Pull request closed without merging**
