### PR TITLE
Execution framework refactoring

### PR DESCRIPTION
**Pull request by d-leroy**
IRunConfiguration:
- removed K3- and Concurrency-specific concepts from IRunConfiguration
and RunConfiguration
- created a K3RunConfiguration extending RunConfiguration and
implementing IK3RunConfiguration (also new) which adds K3-specific
concepts
- moved RunConfiguration from
org.eclipse.gemoc.executionframework.engine.ui to
org.eclipse.gemoc.executionframework.engine

IExecutionContext:
- added IRunconfiguration, IExecutionPlatform and
LanguageDefinitionExtension type parameters to IExecutionContext
- renamed ModelExecutionContext to AbstractModelExecutionContext for
clarity
- added IRunConfiguration type parameter to
SequentialModelExecutionContext

IExecutionEngine:
- added IExecutionContext and IRunConfiguration type parameters to
IExecutionEngine
- PlainK3ExecutionEngine now sets the IExecutionEngine type parameter
to K3RunConfiguration

Other:
- added IExecutionContext to AbstractGemocLauncher
- cleaned up several warnings on the way

As a result, one can now introduce IRunConfiguration,
IExecutionPlatform, LanguageDefinitionExtension and IExecutionContext
subtypes to fit various needs such as new launch configuration
parameters.

### CODE REVIEW

**Comment by ebousse** [comment]
Thanks! Can you report on how much you tested your changes?

**Comment by ebousse** [comment]
Just had a look at the diff, looks good to me. This will give us much more static safety, despite making the code harder to read due to having generics everywhere.

Add a link to a CI build when you have one, and describe some of your tests, and we should merge without too many problems.

Also we might want to find a more precise title for the PR (which will become the squashed commit description).

**Comment by d-leroy** [comment]
CI build: <https://ci.inria.fr/gemoc/job/gemoc-studio-eclipsefork/job/engine-api-refactoring/2/>
I tested  the refactored PlainK3ExecutionEngine on the LegacyFSM language, both in run and debug mode.
In debug mode, I made sure the omniscient debugging operators were working as intended and that the stack and variable view were displaying the correct information.

**Comment by ebousse** [comment]
So it seems other merged PRs created conflicts, can you have a look?

**Comment by d-leroy** [comment]
Done!

**Comment by ebousse** [comment]
@dvojtise I wonder, shouldn't we merge this big API change before making the first release?

**Comment by dvojtise** [comment]
Why not, however, this would imply to postpone the release until some more tests are done. (Ie. open a branch with this content for check on the CI and manual tests)

BTW : @d-leroy  ip-validation doesn't pass have you properly signed, accepted the ECA and make sure that your eclipse account knows about this address : 

> The following users have invalid Signed-off-by footers. Please use the Signed-Off-By (git commit -s) mechanism to confirm the origin of the submission. The identity in the Signed-off-By must match the Author or the Committer. 
> dorian.leroy@tuwien.ac.at

**Pull request merged**
